### ISSUE TITLE
error

### ISSUE THREAD

**Issue by fdu-axiometrics** [nkalinov/ng2-datetime#10]
ERROR in node_modules\ng2-datetime\src\ng2-datetime\ng2-datetime.ts
(25,5): error TS2322: Type 'EventEmitter<{}>' is not assignable to type 'EventEmitter<Date>'.
  Type '{}' is not assignable to type 'Date'.
    Property 'toDateString' is missing in type '{}'.

**Comment by shoudaos** [comment]
The same issue

**Comment by nkalinov** [comment]
I don't have this error, but still, it is safe to ignore it.
Will look at for the next version.
Thanks for reporting it

**Comment by jennet** [comment]
FYI I also have this error reported and it's stopping my project tsc from compiling (even though node_modules is listed in the excluded directories of tsconfig - but that's a different bug for a different dev team!)

Perhaps you can recreate this error if you move the demo to a repo that uses NKDateTime from node_modules rather than the local src directory? As currently the demo doesn't really match what other users' dir structure
