### ISSUE TITLE
Initializing datepicker with custom format and startDate results in empty datetime-box 

### ISSUE THREAD

**Issue by ciesielskico** [nkalinov/ng2-datetime#19]
Hi, 

I am setting the following datepickerOptions in ngOnInit:

.ts
```
this.datepickerOptions = {
      startDate: new Date(),
      autoclose: true,
      todayBtn: 'linked',
      todayHighlight: true,
      language: 'pl',
      icon: 'fa fa-calendar',
      assumeNearbyYear: true,
      format: 'dd.mm.yyyy'
    };

this.transactionDate = new Date()
```

.html
`<datetime #datepicker [(ngModel)]="transactionDate" [datepicker]="datepickerOptions" [timepicker]="timepickerOptions"></datetime>`

Unfortunately the datetime input is empty on initialization. 
Removing the startDate option makes the new Date() visible again. 

I need the datetime picker to only pick future dates. Any advice?

**Comment by ciesielskico** [comment]
Also, initializing this.transactionDate = new Date(); with format 'dd.mm.yyyy' sets the datetime picker to 2nd February 2016 (as of right now).

**Comment by raaaste** [comment]
I have the same problem regarding the format:
`<datetime *ngIf="dateTimePickerOpts" [datepicker]="dateTimePickerOpts.datePickerOpts"  [timepicker]="dateTimePickerOpts.timePickerOpts" [(ngModel)]="startDate"></datetime>`

`dateTimePickerOpts: any = {
    datePickerOpts: {
      format: "dd.mm.yyyy",
    }
}`

The above code produces a date for 07.05.2016 (7th of May 2016) instead of 05.07.2016 (5th of July 2016). The problem seems to originate from ng2-datetime, since [this demo](http://eternicode.github.io/bootstrap-datepicker/) seems to be working just fine. Also changing the format to "dd.yyyy.mm" or "yyyy.mm.dd" produces unwanted results.

ng2-datetime@1.1.1
bootstrap-datepicker@1.6.1

**Comment by ciesielskico** [comment]
Found a workaround/fix:

On line 150 and 165 in `/src/ng2-datetime/ng2-datetime.ts` you have to remove 'en-US' from `date.toLocaleDateString`, now it works correctly.

**Comment by nkalinov** [comment]
Thanks @ciesielskico.
Fixed in 1.1.3

**Comment by ciesielskico** [comment]
@nkalinov Thanks, can you publish to npm? The latest version is still 1.1.2.

**Comment by nkalinov** [comment]
Done
