### ISSUE TITLE
ng2-datetime/node_modules BUG

### ISSUE THREAD

**Issue by Sebastian-G** [nkalinov/ng2-datetime#62]
Reopen! Problem isn't fixed. 
Installed with NPM.
Can't use angular2 on the server anymore.

`"ng2-datetime": "^1.2.0",`

`Uncaught Error: Unexpected value 'NKDatetime' declared by the module 'AppModule'`

https://github.com/nkalinov/ng2-datetime/issues/45

> SOLVED.
> 
> It is a problem in the package.json
> A quick fix will be to remove the ng2-datetime/node_modules subfolder that is being created due to outdated dependencies.

**Comment by rafalkasa** [comment]
Hi @Sebastian-G 

I had the same issue in my application, and after hours of find out what is going on. 
I found strange behavior. When I start using in my angular-cli package.jason = "@angular/<modules>": "~2.0.0", npm install current angular version on this time 2.0.2 and some issue was related to this.

When I change back my configuration in my package.json to @angular/<modules>": "2.0.0"
and after run commands:

```
npm cache clean
npm install
ng serve 
```
go to the web browser and my app start working once again and this strange issue magically disappear. 
Maybe this will help you in your case.

+1 for @Sebastian-G bug because I have the same issue in my application on angular-cli@v1.0.0-beta.17 compile by webpack when I'm using angular version greater then 2.0.0.

**Comment by Sebastian-G** [comment]
Okay Thanks, is it possible to fix the issue for 2.0.1?

**Comment by nkalinov** [comment]
That's normally fixed in 1.2.1. Please verify
